'\" t
.\"     Title: atl
.\"    Author: [see the "Authors" section]
.\"      Date: 04/25/2022
.\"    Manual: Atl Manual
.\"    Source: Atl 0.2.1 BETA
.\"  Language: English
.\"
.TH "ATL" "1" "07/19/2022" "Atl 0\&.3" "Atl Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
atl \- autotool for lazy people
.SH "SYNOPSIS"
.sp
.nf
\fIatl\fR [\-v|\-\-version] [\-v|\-\-help] 
    [COMMAND] [<commands>|<options>] [<args>|<options>]
.fi
.sp
.SH "DESCRIPTION"
.sp
Atl is a tool that can automate console login processes such as git and ssh\&.
.sp
See \fBman atl-git\fR(1) and \fBman atl-ssh\fR(1) to get started\&.
.SH "ATL OPTIONS"
.PP
\fB\-\-version\fR | \fB\-v\fR
.RS 4
Prints the \fIAtl\fR version\&.
.sp
.RE
.PP
\fB\-\-help\fR | \fB\-h\fR
.RS 4
Prints the helper for \fIAtl\fR\&.
.RE
.SH "ATL COMMANDS"
.PP
\fBgit\fR
.RS 4
Runs git suite wrapped by \fIAtl\fR\&.
.sp
.RE
.PP
\fBssh\fR
.RS 4
Runs ssh suite wrapped by \fIAtl\fR\&.
.sp
.RE
.PP
\fBconfig\fR
.RS 4
Runs the configuration routine, must be combined with parameter (\fIgit\fR | \fIssh\fR), which is able to:
.RE
.RS 4
\fBArguments:\fR
.RS 4
.IP \[bu] 2
\fBgit\fR
.RS 4
Runs configure process for the git / github / gitlab account\&.
.RE
.IP \[bu] 2
\fBssh\fR
.RS 4
Runs the configuration process for ssh host warehouse, if the host is not present it will be added,
.RE
.RS 4
otherwise it will be overwritten\&.
.sp
.RE
.RE
.RE
.PP
\fBuninstall\fR
.RS 4
Runs the uninstall script, it will remove selected entry from known hosts\&.
.RE
.RS 4
Can be combined with option (\fI\-\-purge\fR), which is able to remove store ssh-key for ssh conf\&.
.sp
.RE
.PP

.SH "SPECIFIC SUITE COMMANDS"
.sp
See more with \fBman atl-git\fR(1) and \fBman atl-ssh\fR(1)\&.
.sp
.RE
.PP
\fBgit\fR
.RS 4
Can run all git commands/option like \'add\', \'checkout\', \'commit\', \'push\' and so on\&.
.RE
.RS 4
It completely wraps git, manages to invoke the git command with all its options and parameters\&.
.RE
.RS 4
See \fBman git\fR(1) and \fBman git-*\fR(1)\&.
.sp
.RE
.PP
\fBssh\fR
.RS 4
Can run all ssh commands/option\&.
.RE
.RS 4
It completely wraps ssh, manages to invoke the ssh command with all its options and parameters\&.
.RE
.RS 4
See \fBman ssh\fR(1)\&.
.RE
.PP
.SH EXAMPLES
.sp
.RE
.PP
\fBatl git add \&.\fR
.RS 4
See \fBatl git\fR(1) or \fBgit-add\fR(1)\&.
.sp
.RE
.PP
\fBatl git saio \[lq]commit message example\[rq]\fR
.RS 4
See \fBatl git\fR(1)\&.
.sp
.RE
.PP
\fBatl uninstall \-\-purge\fR
.RS 4
Run completely uninstall routine\&.
.sp
.RE
.PP
\fBatl config ssh\fR
.RS 4
Add/remove hosts\&.
.sp
.RE
.PP
\f[B]atl ssh show\f[R]
.RS 4
Prints known hosts\&.
.SH EXIT VALUES
.TP
\f[B]-1\f[R]
.RE
On error\&.
.TP
\f[B]0\f[R]
.RE
On success\&.
.sp
.TP
\f[B]1\f[R]
.RE
When auth is not required\&.
.RE
.SH "AUTHORS"
.sp
Stefano Fattore aka MastroGibbs
.SH "SEE ALSO"
.sp
\fBatl git\fR(1), \fBatl ssh\fR(1)
.SH COPYRIGHT
.PP
Copyright (C) 2022 Stefano Fattore\&.
License GNU GENERAL PUBLIC LICENSE v3\&.
.RE
