#!/bin/bash
#
#
# author stefano fattore
#
# version BETA 0.2.1

signature(){
cat << "EOF"
           configure process for          
                _                  _  _   
               | |                (_)| |  
   __ _  _   _ | |_   ___    __ _  _ | |_ 
  / _` || | | || __| / _ \  / _` || || __|
 | (_| || |_| || |_ | (_) || (_| || || |_ 
  \__,_| \__,_| \__| \___/  \__, ||_| \__|
                             __/ |        
                            |___/   
            
EOF
}

if [ $# == 1 ]; then
    if [ $1 == "--help" ] || [ $1 == "-h" ]; then
        echo "autogitconfigure [options]"
        echo "  --initall"
        echo "      set username and password, check for dep and install them"
        echo
        echo "  --userdata"
        echo "      set username and password"
        echo
        echo "  --deps"
        echo "      check for dep and install them"
        echo
        echo "[WARN] => Must be run as sudo or with root privileges"
        exit 0
    fi
fi

if [ $# -eq 0 ]; then
    echo "[ERR] => No args detected, use --help for tips"
    exit -1
fi

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[ERR] => Not running as root, user root account or sudo"
    exit -1
fi

if [ $# -eq 1 ]; then 
    signature
fi

i=$(who | awk '{print $1}' | head -n 1)

if [[ ! -d "/home/$i/.autogit" ]]
then
    echo "Created /home/$i/.autogit folder.."
    mkdir /home/$i/.autogit
fi

if [[ ! -f "/home/$i/.autogit/supersecrets" ]]
then
    echo "Created /home/$i/.autogit/supersecrets file.."
    touch /home/$i/.autogit/supersecrets
fi

user_data(){
    echo "==============================================="
    echo "          Set up your git credentials"
    echo "==============================================="
    echo

    echo "> Set username: "
    read uname

    echo "> Set password/token: (no-echo)"
    read -s passwd

    echo "" > /home/$i/.autogit/supersecrets

    echo $uname | openssl aes-256-cbc -a -pbkdf2 -salt -pass pass:some > /home/$i/.autogit/supersecrets
    echo $passwd | openssl aes-256-cbc -a -pbkdf2 -salt -pass pass:some >> /home/$i/.autogit/supersecrets
}


dependencies(){
    echo "==============================================="
    echo "          Installing dependencies"
    echo "==============================================="
    echo

    PACKAGE="expect openssl"
    DEB_PACKAGE_NAME="expect openssl"
    FEDORA_PACKAGE_NAME="expect openssl"
    ARCH_PACKAGE_NAME="expect openssl"

    echo "Installing packages $PACKAGE on $(( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1)"
    echo

    if [ -x "$(command -v apt)" ]; then 
        apt update
        apt install -y $DEB_PACKAGE_NAME
    elif [ -x "$(command -v pacman)" ]; then 
        pacman -S $ARCH_PACKAGE_NAME
    elif [ -x "$(command -v dnf)" ]; then
        dnf install $FEDORA_PACKAGE_NAME
    elif [ -x "$(command -v yum)" ]; then
        yum update
        yum install $PACKAGE
    elif [ -x "$(command -v xbps)" ]; then
        xbps-install -Su $PACKAGE
    else 
        echo "OS NOT DETECTED, couldn't install package $PACKAGE"
        exit 1;
    fi

    echo
    echo "==============================================="
    echo "Package $PACKAGE installed successfully"
    echo "==============================================="
}

if [ $1 == "--userdata" ]; then
    user_data
    echo "done"

fi

if [ $1 == "--deps" ]; then
    dependencies

    echo "done"
fi

if [ $1 == "--initall" ]; then
    user_data
    
    dependencies

    echo "done"
fi


