#!/bin/bash
#
#
# author stefano fattore
#
# version BETA 0.3.2

FOLDER="/usr/local/bin"
CONFIGURE="NO"
HELP="NO"
NOSUMAN="NO"

for i in "$@"; do
  case $i in
    -c|--configure)
      CONFIGURE="YES"
      shift 
      ;;
    -p=*|--prefix=*)
      FOLDER="${i#*=}"
      shift 
      ;;
    -h|--help)
      HELP="YES"
      shift 
      ;;
    -*|--*)
      echo "Unknown option $i"
      echo "Please run ./installer --help"
      exit 1
      ;;
    *)
      ;;
  esac
done

if [ ${FOLDER: -1} != "/" ]; then
    FOLDER="${FOLDER}/"
fi

if [[ ! -d $FOLDER ]]
then
    echo "[ERR] => given path -> $FOLDER does not exits, quitting.."
    exit -1
fi

if [ $(whoami) == "root" ]; then
    echo "[ERR] => re-run installer without sudo privileges"
    exit -1
fi

if [ $HELP == "YES" ]; then
    echo "installer [options]"
    echo
    echo "  -c|--configure"
    echo "      initializes the configuration process"
    echo
    echo "  -p|--prefix=<path>"
    echo "      specifies the installation path" 
    echo
    echo "  -h|--help"
    echo "      run helper"
    echo
    exit 0
fi

echo "==============================================="
echo "             Autogit installer"
echo "==============================================="
echo

i=$(whoami)

if ! $(touch "${FOLDER}/test" 2> /dev/null ); then
    echo "Copying the executable into ${FOLDER}.."
    echo "Need sudo privileges to copy the executable.." 
    if ! sudo cp autogit $FOLDER; then
        echo "An error occurred while copying executable, exiting"
        exit -1
    fi
else
    echo "Copying the executable into ${FOLDER}Autogit/bin.."
    if ! rm -f "${FOLDER}test"; then
        echo "An error occurred, exiting"
        exit -1
    fi

    if [[ ! -d "${FOLDER}Autogit" ]]
    then
        if ! mkdir "${FOLDER}Autogit"; then
            echo "An error occurred, exiting"
            exit -1
        fi
    fi

    if [[ ! -d "${FOLDER}Autogit/bin" ]]
    then
        if ! mkdir "${FOLDER}Autogit/bin"; then
            echo "An error occurred, exiting"
            exit -1
        fi
    fi

    if [[ ! -d "${FOLDER}Autogit/man" ]]
    then
        if ! mkdir "${FOLDER}Autogit/man"; then
            echo "An error occurred, exiting"
            exit -1
        fi
    fi

    if [[ ! -d "${FOLDER}Autogit/man/man1" ]]
    then
        if ! mkdir "${FOLDER}Autogit/man/man1"; then
            echo "An error occurred, exiting"
            exit -1
        fi
    fi

    if [[ ! -d "/home/$i/.autogit" ]]
    then
        if ! mkdir /home/$i/.autogit; then
            echo "An error occurred, exiting"
            exit -1
        else
            echo "Created /home/$i/.autogit conf folder.."
        fi
    fi

    if [[ ! -f "/home/$i/.autogit/cache" ]]
    then
        if ! touch /home/$i/.autogit/cache; then
            echo "An error occurred, exiting"
            exit -1
        else
            echo "Created /home/$i/.autogit/cache file.."
        fi
    fi

    if ! echo "${FOLDER}Autogit" > /home/$i/.autogit/cache ; then
        echo "An error occurred, exiting"
        exit -1
    fi

    if ! cp autogit "${FOLDER}Autogit/bin"; then
        echo "An error occurred while copying executable, exiting"
        exit -1
    fi

    {
        NOSUMAN="YES"
        if ! rm -f ${FOLDER}Autogit/man/man1/autogit.1.gz; then
            echo "An error occurred, exiting"
            exit -1
        fi
        if ! cp autogit.1 ${FOLDER}Autogit/man/man1; then
            echo "An error occurred, exiting"
            exit -1
        fi
        if ! gzip ${FOLDER}Autogit/man/man1/autogit.1; then
            echo "An error occurred, exiting"
            exit -1
        fi
        if ! rm -f ${FOLDER}Autogit/man/man1/autogit.1; then
            echo "An error occurred, exiting"
            exit -1
        fi
    } &> /dev/null

    echo "done"
    echo
    echo "Do you want to generate a soft link to /usr/local/bin? needs sudo permissions [y/n]"
    read response 

    if [ $response == "Y" ] || [ $response == "y" ]; then
        if ! sudo ln -sf "${FOLDER}Autogit/bin/autogit" /usr/local/bin/autogit; then
            echo "An error occurred while creating symbolic link, exiting"
            exit -1
        else 
            echo "Soft link created"
        fi
    else
        echo "Generating new soft link aborted."
    fi
fi

echo
echo "Do you want to generate an entry for man? needs sudo permissions [y/n]"
read response 

if [ $response == "Y" ] || [ $response == "y" ]; then
    echo "Generating entry for man.."

    if [[ ! -d "/usr/share/man/man1" ]]
    then
        if ! sudo mkdir /usr/share/man/man1; then
            echo "An error occurred, exiting"
            exit -1
        fi
    fi

    if [ $NOSUMAN == "YES" ]; then
        {
            if ! sudo ln -sf "${FOLDER}Autogit/man/man1/autogit.1.gz" /usr/share/man/man1/autogit.1.gz; then
                echo "An error occurred while generating entry for man, exiting"
                exit -1
            fi
        } &> /dev/null
    else
        {
            if ! sudo cp autogit.1 /usr/share/man/man1; then
                echo "An error occurred while generating entry for man, exiting"
                exit -1
            fi
            if ! sudo gzip /usr/share/man/man1/autogit.1; then
                echo "An error occurred while generating entry for man, exiting"
                exit -1
            fi
            if ! sudo rm -f /usr/share/man/man1/autogit.1; then
                echo "An error occurred while removing autogit cache for man, exiting"
                exit -1
            fi
        } &> /dev/null
    fi
    

    echo
    echo "Running trigger for man-db.."

    {
        if ! sudo mandb; then
            echo "An error occurred while running trigger for man-db, exiting"
            exit -1
        fi
    } &> /dev/null

else
    echo "Generating new entry for man aborted."
fi

echo "done"

if [ $CONFIGURE == "YES" ]; then
    echo
    exec ./autogitconfigure --initall
fi