#!/bin/bash
#
#
# author stefano fattore
#
# version BETA 0.2

if [ $# == 1 ]; then
    if [ $1 == "--help" ] || [ $1 == "-h" ]; then
        echo "installer [options]"
        echo
        echo "  --configure"
        echo "      initializes the configuration process"
        echo
        echo "[WARN] => Must be run as sudo or with root privileges"
        exit 0
    fi
fi

echo "==============================================="
echo "             Autogit installer"
echo "==============================================="
echo

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[ERR] => Not running as root, use user root account or sudo"
    exit -1
fi

echo "Copying the executable into /usr/local/bin.."
sudo cp autogit /usr/local/bin
echo "Copying the unistaller into /usr/local/bin.."
sudo cp uninstall-autogit /usr/local/bin
echo "done"

if [ $# == 1 ]; then
    echo
    if [ $1 == "--configure" ]; then
        exec ./autogitconfigure --initall
    fi
fi