#!/bin/bash
#
#
# author stefano fattore
#
# version BETA 0.1.3

PURGE=0

# ARGS parser
for i in "$@"; do
    COUNT=$((COUNT+1))
    case $i in
        -p|--purge)
            PURGE=1
            shift 
            ;;
        -h|--help)
            echo "uninstall [options]"
            echo
            echo "  -p|--purge"
            echo "      remove installation folder"
            echo
            echo "  -h|--help"
            echo "      run helper"
            echo
            exit 0
            shift 
            ;;
        -*|--*)
            echo "Unknown option $i"
            echo "Please run ./install --help"
            exit 1
            ;;
        *)
            ;;
    esac
done
# ARGS parser end


i=$(who | awk '{print $1}' | head -n 1)
basedir="/home/$i/.atl"
action=0

if [ $PURGE -eq 1 ]; then
    if [[ -f "${basedir}/cache" ]]
    then
        FIND=$(head -n1 ${basedir}/cache)
        if [[ $FIND != "" ]]
        then
            rm -rf $FIND
            action=1
        fi
    fi
fi


if [ $PURGE -eq 1 ]; then
    if [[ -d "/home/$i/.atl" ]]
    then
        echo "Are you sure you want to remove the configuration folder? [y/n]"
        read response

        if [ $response == "y" ] || [ $response == "Y" ]; then
            rm -rf /home/$i/.atl
            action=1
        fi
    fi
fi


if [[ -f "/usr/local/bin/atl" ]]
then
    echo "Removing executable"
    sudo rm -f /usr/local/bin/atl
    action=1
fi

if [[ -f "/usr/share/man/man1/atl.1.gz" ]]
then
    echo "Removing entry for man-db"
    sudo rm -f /usr/share/man/man1/atl.1.gz
    
    echo "Elaborating trigger for man-db"
    {
        if ! sudo mandb; then
            echo "An error occurred while running trigger for man-db, exiting"
            exit -1
        fi
    } &> /dev/null

    action=1
fi

if [ $action -eq 1 ]; then
    echo "done."
else
    echo "nothing to do here."
fi

exit 0