#!/bin/bash
#
#
# author stefano fattore
#
# version BETA 0.2.2


if [ $# == 1 ]; then
    if [ $1 == "--help" ] || [ $1 == "-h" ]; then
        echo "uninstaller-autogit [options]"
        echo
        echo "  --purge"
        echo "      remove conf folder recursively"
        echo
        echo "[WARN] => Must be run as sudo or with root privileges"
        exit 0
    fi
fi


if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[ERR] => Not running as root, use user root account or sudo"
    exit -1
fi

echo "==============================================="
echo "             Autogit unistaller"
echo "==============================================="
echo

echo "unistalling autogit.."

sudo rm -f /usr/local/bin/autogit
sudo rm -f /usr/local/bin/uninstall-autogit

if [[ $1 == "--purge" ]]
then
    echo "removing conf folder.."
    i=$(whoami)
    if [[ -d "/home/$i/.autogit" ]]
    then
        rm -f -r /home/$i/.autogit
    fi
fi

echo "done"